### ISSUE TITLE
Upgrade from FPP 5.5 to FPP 6.1.1 broke plugin (uninstall/reinstall to fix)

### ISSUE THREAD

**Issue by ShadowLight8** [ShadowLight8/Dynamic_RDS#11]
Was on FPP 5.5 with the plugin working. Ran the Upgrade OS option to go to FPP 6.1.1. This caused the plugin to fail after the upgrade. Main reason was the smbus python library was removed during the upgrade. Tried to check for a plugin upgrade in the plugin manager and got a message that the git fetch failed. Uninstalled and reinstalled fixed the issue. smbus is installed as part of the fpp_install.sh script.

Not sure how to resolve this, but documenting it here in case others encounter this.

**Comment by ShadowLight8** [comment]
This also removed the PWM config from /boot/config.txt

**Comment by ShadowLight8** [comment]
Need to look into how to set up PWM programmatically. Also, minor errors occur at shutdown if PWM isn't enabled:
```
Traceback (most recent call last):
  File "/home/fpp/media/plugins/Dynamic_RDS/./Dynamic_RDS_Engine.py", line 574, in <module>
    transmitter.shutdown()
  File "/home/fpp/media/plugins/Dynamic_RDS/./Dynamic_RDS_Engine.py", line 275, in shutdown
    with open("/sys/class/pwm/pwmchip0/pwm0/duty_cycle", 'w') as p:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/pwm/pwmchip0/pwm0/duty_cycle'
```

**Comment by ShadowLight8** [comment]
Will pull fix from https://github.com/ShadowLight8/Si4713_FM_RDS/pull/19 into this plugin to handle smbus missing

**Comment by ShadowLight8** [comment]
Reinstall process for smbus is looking good.

Programmatically updating the PWM config in /boot/config.txt is the other remaining half of this issue.

**Comment by ShadowLight8** [comment]
Framework for being able to enable PWM is in progress in #27

**Comment by ShadowLight8** [comment]
With merge of #27, all functionality of this issue are covered. Testing is still needed on an OS upgrade to close this.

**Comment by ShadowLight8** [comment]
Ran OS upgrade from 7.3 to 7.4. After initial reboot, config page showed:
![image](https://github.com/ShadowLight8/Dynamic_RDS/assets/25712519/8a6397a1-8d35-45aa-b770-b83bfd1f4354)
Started with re-running install script
![image](https://github.com/ShadowLight8/Dynamic_RDS/assets/25712519/6a01cd93-8587-43ea-9b3a-5f482d2018c5)
Toggled Hardware PWM and rebooted
![image](https://github.com/ShadowLight8/Dynamic_RDS/assets/25712519/9f9ea9c4-953c-4800-80d9-703fac937636)

**Comment by ShadowLight8** [comment]
Successfully tested. Closing.
